# Generated by Django 4.0.1 on 2022-01-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_ASM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1500, verbose_name='code')),
                ('line_count', models.IntegerField(max_length=5, verbose_name='lines')),
            ],
        ),
        migrations.CreateModel(
            name='Code_BIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1500, verbose_name='code')),
                ('asm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembler.code_asm')),
            ],
        ),
    ]
